---
version: 2
jobs:
  build:
    working_directory: ~/krill
    docker:
      - image: circleci/node:8.2.1
      - image: rabbitmq:3.6.10-alpine
    steps:
      - checkout
      - restore_cache:
          keys: dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          keys: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: npm test